version: '3.8'

services:
 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb-config:/data/configdb
 notes:
  build:
   context: .
   dockerfile: ./Dockerfile
  ports:
   - 8000:8000
   - 9229:9229
  environment:
   - SERVER_PORT=8000
   - CONNECTIONSTRING=mongodb://mongo:27017/notes
  volumes:
   - ./:/app
   - /app/node_modules
  # command: npm run debug

volumes:
 mongodb:
 mongodb-config: