apiVersion: v1
kind: Service
metadata:
  name: node-docker-service
  namespace: dev
spec:
  selector:
    app: node-docker
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP